/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vEU7LntD2rfdBHtDX5FyyK

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantswAhdbqxTi9Jh } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wAhdbqxTi9Jh/globalVariant
import {
  UnnamedGlobalGroupOfVariants2Value,
  useUnnamedGlobalGroupOfVariants2
} from "./PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants2"; // plasmic-import: GsMvHMTe0oy_/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantswAhdbqxTi9Jh,
  unnamedGlobalGroupOfVariants2: useUnnamedGlobalGroupOfVariants2
});
